### ISSUE TITLE
Step size strategy in code and in paper

### ISSUE THREAD

**Issue by postrou** [konstmish/random_reshuffling#2]
Hi!
I've been looking through your code, trying to understand the adaptive step size procedure, and there are couple of things, that I do not understand. If you could clarify me these, it would be the best.
1. In some cases you use theoretic smoothness constant $L_f$ for logistic regression, and sometimes - its batch approximation (I will denote it as $L_b$). For example, for the regularization constant, that is $\lambda = L / \sqrt N$, you use $L=L_f$. But when you choose step size (Section 5) $\gamma_k = \\{1/L, ...\\}$, you use $L=L_b$. Shouldn't you use $L_b$ in both cases?
2. As far as I understand, in the equation for $\gamma_k$ you take $\mu \equiv \lambda$. And if so, then in your code 
$$\gamma_k = \min \left\\{ \frac{1}{L}, \frac{1}{\lambda + \lambda / 3 \cdot \max\\{0, k-k_0\\}} \right\\} = \min \left\\{ \frac{1}{L}, \frac{1}{\lambda \max\\{1, \frac{k-k_0}{3} + 1\\}} \right\\}$$
which is not equal to
$$\gamma_k = \min \left\\{ \frac{1}{L}, \frac{3}{\lambda \max\\{1, k-k_0\\}} \right\\}$$
from the paper.

**Comment by konstmish** [comment]
Hi Petr, sorry for the late response.  
1. I don't have a strong opinion on this, my main reason to use $L_f$ when setting the regularization is to keep the experiments consistent: I don't want to change the problem depending on the batch size, I want it to be the same to isolate the impact of batch size only on the method's performance. This is important for instance when comparing the performance of the same method with different batch sizes.
2. You seem to be right about the difference between the values, but I also think it wouldn't matter in practice because the value $\max\\{1, k - k_0 + 3\\}$ should be almost the same as $\max \\{1, k - k_0 \\}$ for all $k$ except when $k - k_0\in [-1,10 ] $, which is just a few iterations.

**Comment by postrou** [comment]
Ok, thank you for the clarification!
